### ISSUE TITLE
About the directory, hotimport cannot get the right path

### ISSUE THREAD

**Issue by lijiarui** [zixia/hot-import#5]
My directory as follows
```
├── src
│   ├── bot.ts
│   ├── logic
│   │   └── root.ts
├── tsconfig.json
└── tslint.json
```
-------
In the file  `bot.ts` I add 
```ts
await hotImport('./logic/root')
```
then run `ts-node src/bot.ts`, I get the following error
```
01:47:54 ERR Bot Error: Cannot find module '/Users/jiaruili/git/ticket-bot/internal/process/logic/root'
```
Actually, there isn't `internal/process/` under my folder.

---------
Then I change the command as follows:
```ts
await hotImport('../../src/logic/root')
```
It works well, I think there may be some path problem here, but I don't know what happened.

**Comment by lijiarui** [comment]
The following is my mac system.

When I tried on cloud9 (ubuntu system), it work as expect, say, using 
```ts
await hotImport('./src/logic/root')
```
can work. but using mac directory cannot work...

**Comment by huan** [comment]
Please provide the steps to reproduce this problem.

**Comment by lijiarui** [comment]
sorry, I found this is my bug....

**Comment by huan** [comment]
Please do double/triple check before submitting any issues to prevent wasting others' time.

And also good for your credit.
